### ISSUE TITLE
Assumption on executable name?

### ISSUE THREAD

**Issue by aubertc** [jweeks2023/LQICM-Benchmark#10] opened 2023-06-22 19:42 UTC
I have followed (I believe) pretty closely the readme by

1. Editing the compiler name to gcc in benchmark.c,
2.  Compiled with `gcc benchmark.c -o benchmark -lm`,
3. Executed `./benchmark`

But I received many errors about 

> sh: 1: ./CodeToTest/testExe: not found

I assume that benchmark.c is making assumptions about the name of the executable outputted by the compiler that are not correct when gcc is used.
Could you either confirm, or "hard-code" the name of the executable (I believe `-o` should do the trick. By default gcc uses `a.out`).

**Comment by jweeks2023** [comment] 2023-06-23 16:46
The way the benchmark compiles the program specifies the output name `testExe`. You can see this occur here: 
https://github.com/jweeks2023/LQICM-Benchmark/blob/41ba8b7b82abae50c0256153e99c3d9d4d22cd32/benchmark.c#L313-L314

The string that should result from this should look something like `../../../usr/bin/clang-15 ./CodeToTest/[FILENAME] -O0 -o ./CodeToTest/testExe`
Since it's saying that the test file doesn't exist, then that likely means that the program you're attempting to measure failed to compile.
I believe this may be due to how I sized the char array that stores the command, since I have it as 100. Long names or filepaths may result in the command being truncated (as is by design, thanks to snprintf). Editing the array size should fix that.

Fixed with https://github.com/jweeks2023/LQICM-Benchmark/commit/8a61b44bba365d47d46cb5d11aaeb86409e3fe2e

**Closed as completed by jweeks2023** 2023-06-23 16:46 UTC

**Comment by aubertc** [comment] 2023-06-23 19:54
Ok, it worked. Question: why not

```
#define COMPILERPATH	"/usr/bin/"	//filepath of the compiler defined above (default: "../../../usr/bin/")
```

instead of your relative path? That would be much more portable!

**Comment by jweeks2023** [comment] 2023-06-24 01:03
In my case, since I'm using WSL, the root directory for me is `/home/[USERNAME]/`. Since I'm working within the LQICM directory as well, that gets me one directory deeper from "true root", hence my current fix. I think it's still a good idea to do it your way, so I'll change it for the sake of portability.
